apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    api: clusterapi
    k8s-app: ipam-controller
  name: machine-ipam-controllers
  namespace: openshift-machine-api
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      api: clusterapi
      k8s-app: ipam-controller
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      name: machine-ipam-controller
      namespace: openshift-machine-api
      labels:
        api: clusterapi
        k8s-app: ipam-controller
    spec:
      containers:
        - image: quay.io/ocp-splat/machine-ipam-controller:latest
          imagePullPolicy: Always
          name: machine-ipam-controller
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
          volumeMounts:
            - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              name: kube-api-access-8tcfz
              readOnly: true
      nodeSelector:
        node-role.kubernetes.io/master: ""
      restartPolicy: Always
      serviceAccount: machine-ipam-controller
      serviceAccountName: machine-ipam-controller
      # terminationGracePeriodSeconds: 30
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 300
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 300
        - effect: NoSchedule
          key: node.kubernetes.io/memory-pressure
          operator: Exists
      volumes:
        - name: kube-api-access-8tcfz
          projected:
            defaultMode: 420
            sources:
              - serviceAccountToken:
                  expirationSeconds: 3607
                  path: token
              - configMap:
                  items:
                    - key: ca.crt
                      path: ca.crt
                  name: kube-root-ca.crt
              - downwardAPI:
                  items:
                    - fieldRef:
                        apiVersion: v1
                        fieldPath: metadata.namespace
                      path: namespace
              - configMap:
                  items:
                    - key: service-ca.crt
                      path: service-ca.crt
                  name: openshift-service-ca.crt