apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: redis-template
  annotations:
    description: "Description"
    iconClass: "icon-redis"
    tags: "database,nosql"
objects:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: machine-ipam-controller
      namespace: openshift-machine-api
      annotations:
        include.release.openshift.io/self-managed-high-availability: "true"
        include.release.openshift.io/single-node-developer: "true"
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: machine-ipam-controller
      annotations:
        include.release.openshift.io/self-managed-high-availability: "true"
        include.release.openshift.io/single-node-developer: "true"
    rules:
      - apiGroups:
          - ipamcontroller.openshift.io
        resources:
          - ippools
        verbs:
          - get
          - list
          - patch
          - watch
      - apiGroups:
          - ipam.cluster.x-k8s.io
        resources:
          - ipaddressclaims
          - ipaddressclaims/status
        verbs:
          - "*"
      - apiGroups:
          - ipam.cluster.x-k8s.io
        resources:
          - ipaddresses
        verbs:
          - "*"
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: machine-ipam-controller
      annotations:
        include.release.openshift.io/self-managed-high-availability: "true"
        include.release.openshift.io/single-node-developer: "true"
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: machine-ipam-controller
    subjects:
      - kind: ServiceAccount
        name: machine-ipam-controller
        namespace: openshift-machine-api
  - apiVersion: ipamcontroller.openshift.io/v1
    kind: IPPool
    metadata:
      namespace: openshift-machine-api
      name: static-ci-pool
    spec:
      address-cidr: 192.168.${THIRD_OCTET}.128/29
      prefix: 23
      gateway: 192.168.${THIRD_OCTET}.1
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        api: clusterapi
        k8s-app: machine-ipam-controller
      name: machine-ipam-controllers
      namespace: openshift-machine-api
    spec:
      progressDeadlineSeconds: 600
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        matchLabels:
          api: clusterapi
          k8s-app: machine-ipam-controller
      strategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
        type: RollingUpdate
      template:
        metadata:
          name: machine-ipam-controller
          namespace: openshift-machine-api
          labels:
            api: clusterapi
            k8s-app: machine-ipam-controller
        spec:
          containers:
            - image: quay.io/ocp-splat/machine-ipam-controller:latest
              imagePullPolicy: Always
              name: machine-ipam-controller
              resources:
                requests:
                  cpu: 10m
                  memory: 100Mi
              volumeMounts:
                - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
                  name: kube-api-access-8tcfz
                  readOnly: true
          nodeSelector:
            node-role.kubernetes.io/master: ""
          restartPolicy: Always
          serviceAccount: machine-ipam-controller
          serviceAccountName: machine-ipam-controller
          # terminationGracePeriodSeconds: 30
          tolerations:
            - key: CriticalAddonsOnly
              operator: Exists
            - effect: NoSchedule
              key: node-role.kubernetes.io/master
              operator: Exists
            - effect: NoExecute
              key: node.kubernetes.io/not-ready
              operator: Exists
              tolerationSeconds: 300
            - effect: NoExecute
              key: node.kubernetes.io/unreachable
              operator: Exists
              tolerationSeconds: 300
            - effect: NoSchedule
              key: node.kubernetes.io/memory-pressure
              operator: Exists
          volumes:
            - name: kube-api-access-8tcfz
              projected:
                defaultMode: 420
                sources:
                  - serviceAccountToken:
                      expirationSeconds: 3607
                      path: token
                  - configMap:
                      items:
                        - key: ca.crt
                          path: ca.crt
                      name: kube-root-ca.crt
                  - downwardAPI:
                      items:
                        - fieldRef:
                            apiVersion: v1
                            fieldPath: metadata.namespace
                          path: namespace
                  - configMap:
                      items:
                        - key: service-ca.crt
                          path: service-ca.crt
                      name: openshift-service-ca.crt
parameters:
  - name: THIRD_OCTET
    description: The value used in the third octet of the IP cidr.
